### ISSUE TITLE
Add an Auto categorize feature like IDM and FDM

### ISSUE THREAD

**Issue by Khalylexe** [amir1376/ab-download-manager#63] opened 2024-09-06 10:23 UTC
I like how IDM and FDM use folders to organize files according to their type
so like:
for zip,rar > Compressed
for mp3 > Music
for exe,msi > Programs
and so on
it would be a really good QOL feature

**Comment by amir1376** [comment] 2024-09-07 16:06
@Khalylexe Hi there thank you. I think this is duplicate of #26.

**Closed by amir1376** 2024-09-07 16:06 UTC
